version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
#    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-subscription-service-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
   #   volume для хранения данных БД, при надобности раскомментировать.
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: app
    image: user_subscriptions_service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user-subscription-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_ENABLED: "true"

volumes:
    postgres_data:

