server:
  port: 8080

spring:
  application:
    name: app

  #  (Data source)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-subscription-service-db
#    url: jdbc:postgresql://localhost:5433/user-subscription-service-db
    username: postgres
    password: postgres
    flyway:
      enabled: true
      locations: classpath:db/migration
#      baseline-on-migrate: true
#      clean-disabled: true

  jpa:
    hibernate:
      ddl-auto: none
#    срабатывает после flyway/ отключен... т.к. затирает данные
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: thread


logging:
  level:
    ROOT: INFO



